# Generated by Django 4.1.7 on 2023-03-04 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0007_answer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
    ]
